on:
  push:
    branches: main

name: Render, Encrypt, and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install StatiCrypt
        run: npm install -g staticrypt

      - name: Render Quarto
        # This creates the _site folder with your normal HTML
        run: quarto render

     - name: Encrypt HTML files
        run: |
          for file in $(find _site -name "*.html"); do
            # -o specifies the output filename. 
            # By setting it to the same name, we overwrite the original.
            staticrypt "$file" -p "@64TentsmuirCycle" -o "$file"
          done

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          # render: false is CRITICAL here so it uses our encrypted files
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}